Fix undefined method error: _getStoredContent -> getGeneratedEntryAsync
The previous commit introduced a call to this._getStoredContent which doesn't
exist. The correct method is getGeneratedEntryAsync.

This was causing all LLM generation to fail with:
"this._getStoredContent is not a function (it is undefined)"